-- Skillspoints database schema for Supabase PostgreSQL.
-- Run this file in Supabase SQL Editor before starting the Next.js app.
-- The app currently authenticates against "User" itself, so password values
-- must be bcrypt hashes and should never be exposed through the Data API.

create table if not exists public."User" (
  "idUser" integer generated by default as identity primary key,
  "name" text not null,
  "email" text not null unique,
  "password" text not null,
  "totalPoints" integer not null default 0,
  "createdAt" timestamptz(3) not null default now()
);

create table if not exists public."MicroCourse" (
  "idMicroCourse" integer generated by default as identity primary key,
  "title" text not null,
  "description" text,
  "createdAt" timestamptz(3) not null default now(),
  "creatorId" integer not null
    references public."User" ("idUser")
);

create table if not exists public."Learning" (
  "idLearning" integer generated by default as identity primary key,
  "userId" integer not null
    references public."User" ("idUser"),
  "microCourseId" integer not null
    references public."MicroCourse" ("idMicroCourse"),
  "startDate" timestamptz(3) not null default now(),
  "status" text not null
);

create table if not exists public."Reward" (
  "idReward" integer generated by default as identity primary key,
  "name" text not null,
  "description" text,
  "requiredPoints" integer not null,
  "availableQuantity" integer
);

create table if not exists public."RewardHistory" (
  "idHistory" integer generated by default as identity primary key,
  "userId" integer not null
    references public."User" ("idUser"),
  "rewardId" integer not null
    references public."Reward" ("idReward"),
  "obtainedAt" timestamptz(3) not null default now()
);

-- Foreign-key indexes keep course, learning, and reward-history queries fast.
create index if not exists "MicroCourse_creatorId_idx"
  on public."MicroCourse" ("creatorId");

create index if not exists "Learning_userId_idx"
  on public."Learning" ("userId");

create index if not exists "Learning_microCourseId_idx"
  on public."Learning" ("microCourseId");

create index if not exists "RewardHistory_userId_idx"
  on public."RewardHistory" ("userId");

create index if not exists "RewardHistory_rewardId_idx"
  on public."RewardHistory" ("rewardId");

-- Keep these tables protected when they are exposed through Supabase APIs.
-- The Next.js server should connect with the database connection string or a
-- server-only Supabase key. No public policies are added because this project
-- does not currently map rows to auth.users.
alter table public."User" enable row level security;
alter table public."MicroCourse" enable row level security;
alter table public."Learning" enable row level security;
alter table public."Reward" enable row level security;
alter table public."RewardHistory" enable row level security;

-- Allow the Prisma/server database role to use the tables and identity
-- sequences. RLS does not restrict the service_role or table owner.
grant usage on schema public to service_role;
grant select, insert, update, delete on table
  public."User",
  public."MicroCourse",
  public."Learning",
  public."Reward",
  public."RewardHistory"
to service_role;

grant usage, select on all sequences in schema public to service_role;

-- Quick verification after running the script.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('User', 'MicroCourse', 'Learning', 'Reward', 'RewardHistory')
order by table_name;